### PR TITLE
Add language_map option

### PR DESCRIPTION
**Pull request by bpierre**
This allows to map any vim filetype to a [Carbon language](https://github.com/carbon-app/carbon/blob/2cbdcd0cc23d2d2f23736dd3cfbe94134b141191/lib/constants.js#L624-L1048).

Example:

```lua
require('carbon-now').setup({
  language_map = {
    typescriptreact = "typescript"
  },
})
```

Or with a function:

```lua
require('carbon-now').setup({
  language_map = function(filetype)
    if (filetype == "typescriptreact") then
      return "typescript"
    end
  end
})
```

A map of known filetypes has also been added, only containing `typescriptreact` and `javascriptreact` for now.

### CODE REVIEW

**Comment by ellisonleao** [comment]
@bpierre thanks for the PR, but isn't [vim.filetype](https://neovim.io/doc/user/lua.html#vim.filetype) resolving that same problem?

**Comment by bpierre** [comment]
Not completely sure but I think `vim.filetype` only allows to define `file pattern => vim filetype` mappings, while this PR allows to define a `vim filetype => carbon filetype` mappings (with a fallback to the vim filetype).

**Comment by ellisonleao** [comment]
@bpierre got it. How about making that change only internally. I still think if we make it as a config can lead to a lot user mistakes. How about creating a internal mapping and making that same from => to logic for those special cases?

**Comment by bpierre** [comment]
That could be a solution yes, though I think it could lead to issues for some people since Neovim filetypes are arbitrary (even though users, plugins etc. generally tend to agree on the same names). Also Carbon could add new languages at any point, having this option would allow to use them without having to wait for a carbon-now.vim update.

Another solution could also be to put `language_map` inside an `advanced` field to make it clear that it shouldn’t be needed in most cases:

```lua
{
  advanced = {
    language_map = {},
    open_cmd = "…", -- open_cmd could be considered advanced too if #8 gets merged
    base_url = "…" -- base_url could also be considered an advanced use case
  }
}
```

Another one would be to put an “Advanced” section in the documentation to separate `language_map` and maybe also `base_url` / `open_cmd` from the theming options?

Let me know what would be your preferred solution and I’ll make the changes.

**Comment by ellisonleao** [comment]
@bpierre not a big fan of too nested configs, but i get the point. Let's keep it simple for now and just make the internal changes (i am ok with checking new languages in carbon if needed)

**Comment by bpierre** [comment]
Cool I’ll make the change :+1:

**Comment by bpierre** [comment]
@ellisonleao done :hugs:

**Pull request merged**
